version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: deploy/beforeInstall
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy/AfterInstall
      timeout: 300
      runas: ubuntu
