version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: AWS/beforeInstall.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: AWS/AfterInstall.sh
      timeout: 300
      runas: ubuntu
