version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location:beforeInstall
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location:AfterInstall
      timeout: 300
      runas: ubuntu
